site_name: Kotobase Docs
#site_url: https://svdc1.github.io/kotobase
site_dir: site
repo_url: https://github.com/svdC1/kotobase
repo_name: svdC1/kotobase
theme:
  name: material
  font:
    code: Roboto Mono
  features:
    - header.autohide
    - navigation.footer
    - search.suggest
    - search.highlight
    - navigation.sections
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: black
      accent: deep purple

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://docs.sqlalchemy.org/en/20/objects.inv
          options:
            show_root_heading: true
            show_root_toc_entry: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
            docstring_section_style: table
            show_root_full_path: false
            show_object_full_path: false
            show_root_members_full_path: false
            show_source: false

          paths: ["../kotobase/src"]

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink
