name: docs

on:
    release:
        types: [published]
    push:
        paths:
            - "docs-site/**"
            - ".github/workflows/docs.yml"

    workflow_dispatch:

permissions:
    contents: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
                  cache: pip

            # 3 Install docs dependencies
            - name: Install documentation tool-chain
              run: |
                  python -m pip install -r docs-site/requirements.txt
                  python -m pip install kotobase

            # 4 Build the static site
            - name: Build MkDocs site
              run: mkdocs build -f docs-site/mkdocs.yml

            # 5 Deploy to GitHub Pages
            - name: Deploy to gh-pages
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: mkdocs gh-deploy -f docs-site/mkdocs.yml --force
