name: Build and Upload Kotobase Database

on:
    schedule:
        # Every Sunday Night
        - cron: "0 0 * * 0"
    workflow_dispatch:

jobs:
    build-and-upload:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  pip install -e ./kotobase

            - name: Build the database
              run: |
                  kotobase build

            - name: Authenticate with Google
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: "${{ secrets.GCP_SA_KEY }}"

            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v1

            - name: Upload to Google Drive
              run: |
                  gcloud drive files update "1Ejio0X_tcSszt_0nIhJsBqdi-sKfbKqq" kotobase/src/kotobase/db/kotobase.db --mime-type "application/x-sqlite3"
