name: Build and Upload Kotobase Database

on:
    schedule:
        # Every Sunday Night
        - cron: "0 0 * * 0"
    workflow_dispatch:

jobs:
    build-and-upload:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  pip install kotobase

            - name: Build the database
              run: |
                  kotobase build

            - name: Upload to Google Drive
              env:
                  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
                  DRIVE_FILE_ID: "1Ejio0X_tcSszt_0nIhJsBqdi-sKfbKqq"
              run: |
                  pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
                  python .github/scripts/upload_drive.py
